language: elixir
elixir:
  - 1.6.6
otp_release:
  - 20.2
before_install:
dist: trusty
cache: apt
env:
  global:
    - PGVERSION=9.6
  matrix:
    - MIX_ENV=dev
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
before_script:
  - mix compile
  - psql -c "CREATE DATABASE internal_db;" -U postgres
  - psql -c "CREATE DATABASE postgres_cluster;" -U postgres
  - psql -c "CREATE USER ps_internal WITH PASSWORD 'mysecretpassword1';" -U postgres
  - psql -c "ALTER USER ps_internal CREATEDB;" -U postgres
  - psql -c "CREATE USER ps_cluster WITH PASSWORD 'mysecretpassword2';" -U postgres
  - psql -c "ALTER USER ps_cluster CREATEDB;" -U postgres
script:
  - MIX_ENV=dev mix test
  - mix ecto.create
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  recipients:
    - paracetamolboy@gmail.com