language: elixir
elixir:
  - 1.6.6
otp_release:
  - 20.3
dist: trusty
cache: apt
env:
  matrix:
    - MIX_ENV=test
services:
  - docker
before_install:
  - docker network create --driver bridge postgrix || true
  - docker run --rm --name internal_db --network postgrix -p 5433:5432 -e POSTGRES_USER=ps_internal -e POSTGRES_PASSWORD=mysecretpassword1 -e POSTGRES_DB=internal_db -d postgres:9.6 -c logging_collector=on
  - docker run --rm --name postgres_cluster --network postgrix -p 5434:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=mysecretpassword2 -e POSTGRES_DB=postgres_cluster -d -v $TRAVIS_BUILD_DIR/cert.pem:/var/lib/postgresql/server.crt -v $TRAVIS_BUILD_DIR/cert-key.pem:/var/lib/postgresql/server.key postgres:9.6 -c logging_collector=on -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
  - docker run --rm --name vault --network postgrix -p 8200:8200 --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -e 'VAULT_ADDR=http://127.0.0.1:8200' -d vault
  - docker exec -ti vault sh -c "vault login token=myroot && vault audit enable file file_path=/vault/logs/vault_audit.log && vault secrets enable database"
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
  - mix format --check-formatted
  - mix credo
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  recipients:
    - paracetamolboy@gmail.com