language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_install:


dist: trusty
cache: apt
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.4.5
  - otp_release: 19.3
    elixir: 1.5.3
env:
  global:
    - PGVERSION=9.6
  matrix:
    - MIX_ENV=test
    - MIX_ENV=pg PGVERSION=9.2
    - MIX_ENV=pg
    - MIX_ENV=mysql
install:
  - mix local.hex --force
  - mix deps.get
before_script:
  - psql -c "CREATE DATABASE testpostgres;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'mysecretpassword';" -U postgres
script:
  - ECTO_POOL=poolboy mix test
  - ECTO_POOL=sbroker mix test
  - mix ecto.create
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - paracetamolboy@gmail.com